---
sidebar: sidebar 
permalink: data-analytics/bda-ai-business-benefits.html 
keywords: business, benefits 
summary: In questa sezione vengono descritti i vantaggi aziendali di questa soluzione. 
---
= Vantaggi aziendali
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Il passaggio dei dati dall'analisi dei big data all'intelligenza artificiale offre i seguenti vantaggi:

* La capacità di estrarre dati da diversi file system Hadoop e GPFS in un sistema di archiviazione NFS unificato
* Un modo automatizzato e integrato con Hadoop per trasferire dati
* Una riduzione del costo di sviluppo della libreria per lo spostamento dei dati dai file system Hadoop
* Massime prestazioni tramite throughput aggregato di più interfacce di rete da un'unica fonte di dati utilizzando NIPAM
* Metodi programmati e su richiesta per trasferire i dati
* Efficienza di archiviazione e capacità di gestione aziendale per dati NFS unificati mediante l'utilizzo del software di gestione dati ONTAP
* Costo zero per lo spostamento dei dati con il metodo Hadoop per il trasferimento dei dati

