---
sidebar: sidebar 
permalink: data-analytics/confluent-kafka-conclusion.html 
keywords: conclusion 
summary: 'Questo documento fornisce linee guida sulle best practice per l"utilizzo di Kafka con lo storage NetApp , inclusi test di certificazione Confluent Kafka, risultati delle prestazioni, ottimizzazione, connettori Kafka e la funzionalità di auto-ribilanciamento.' 
---
= Conclusione
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Questo documento fornisce linee guida sulle best practice per l'utilizzo di Confluent Tiered Storage con storage NetApp , inclusi test di verifica, risultati delle prestazioni dello storage a livelli, ottimizzazione, connettori Confluent S3 e funzionalità di autobilanciamento.  Considerando le policy ILM, le prestazioni di Confluent con più test delle prestazioni per la verifica e le API S3 standard del settore, l'archiviazione di oggetti NetApp StorageGRID è la scelta ottimale per l'archiviazione a livelli di Confluent.



== Dove trovare ulteriori informazioni

Per saperne di più sulle informazioni descritte nel presente documento, consultare i seguenti documenti e/o siti web:

* Che cos'è Apache Kafka
+
https://www.confluent.io/what-is-apache-kafka/["https://www.confluent.io/what-is-apache-kafka/"^]

* Documentazione del prodotto NetApp
+
https://www.netapp.com/support-and-training/documentation/["https://www.netapp.com/support-and-training/documentation/"^]

* Dettagli dei parametri del sink S3
+
https://docs.confluent.io/kafka-connect-s3-sink/current/configuration_options.html["https://docs.confluent.io/kafka-connect-s3-sink/current/configuration_options.html#s3-configuration-options"^]

* Apache Kafka
+
https://en.wikipedia.org/wiki/Apache_Kafka["https://en.wikipedia.org/wiki/Apache_Kafka"^]

* Archiviazione infinita nella piattaforma Confluent
+
https://www.confluent.io/blog/infinite-kafka-storage-in-confluent-platform/["https://www.confluent.io/blog/infinite-kafka-storage-in-confluent-platform/"^]

* Confluent Tiered Storage: best practice e dimensionamento
+
https://docs.confluent.io/platform/current/kafka/tiered-storage.html#best-practices-and-recommendations["https://docs.confluent.io/platform/current/kafka/tiered-storage.html#best-practices-and-recommendations"^]

* Connettore sink Amazon S3 per Confluent Platform
+
https://docs.confluent.io/kafka-connect-s3-sink/current/overview.html["https://docs.confluent.io/kafka-connect-s3-sink/current/overview.html"^]

* Dimensionamento di Kafka
+
https://eventsizer.io["https://eventsizer.io"]

* Dimensionamento StorageGRID
+
https://fusion.netapp.com/["https://fusion.netapp.com/"^]

* Casi d'uso di Kafka
+
https://kafka.apache.org/uses["https://kafka.apache.org/uses"^]

* Cluster Kafka autobilancianti nella piattaforma confluente 6.0
+
https://www.confluent.io/blog/self-balancing-kafka-clusters-in-confluent-platform-6-0/["https://www.confluent.io/blog/self-balancing-kafka-clusters-in-confluent-platform-6-0/"^]

+
https://www.confluent.io/blog/confluent-platform-6-0-delivers-the-most-powerful-event-streaming-platform-to-date/["https://www.confluent.io/blog/confluent-platform-6-0-delivers-the-most-powerful-event-streaming-platform-to-date/"^]

* Esempi di clienti Instaclustr e dettagli sui loro casi d'uso
+
https://www.instaclustr.com/blog/netapp-and-pegasystems-open-source-support-package/[], https://www.instaclustr.com/wp-content/uploads/Insta_Case_Study_Pegasystems_1_21sep25.pdf[]

+
https://www.instaclustr.com/resources/customer-case-study-pubnub/[]

+
https://www.instaclustr.com/resources/customer-case-study-tesouro/[]


