---
sidebar: sidebar 
permalink: data-analytics/confluent-kafka-solution.html 
keywords: solution, architecture, details, hardware, software 
summary: 'Questa sezione riguarda l"hardware e il software utilizzati per la certificazione Confluent.  Queste informazioni sono applicabili alla distribuzione di Kafka con storage NetApp .' 
---
= Dettagli dell'architettura della soluzione
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Questa sezione riguarda l'hardware e il software utilizzati per la verifica Confluent.  Queste informazioni sono applicabili alla distribuzione della piattaforma Confluent con storage NetApp .  La tabella seguente illustra l'architettura della soluzione testata e i componenti di base.

|===
| Componenti della soluzione | Dettagli 


| Confluent Kafka versione 6.2  a| 
* Tre guardiani dello zoo
* Cinque server broker
* Cinque server di strumenti
* Una Grafana
* Un centro di controllo




| Linux (Ubuntu 18.04) | Tutti i server 


| NetApp StorageGRID per l'archiviazione a livelli  a| 
* Software StorageGRID
* 1 x SG1000 (bilanciatore di carico)
* 4 x SGF6024
* 4 x 24 x 800 SSD
* Protocollo S3
* 4 x 100 GbE (connettività di rete tra broker e istanze StorageGRID )




| 15 server Fujitsu PRIMERGY RX2540 | Ciascuno dotato di: * 2 CPU, 16 core fisici totali * Intel Xeon * 256 GB di memoria fisica * Doppia porta 100 GbE 
|===