---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'netapp, solutions, ai, what"s new, updates, change log' 
summary: Registro delle recenti modifiche apportate al materiale collaterale delle soluzioni di intelligenza artificiale NetApp . 
---
= Novità nelle soluzioni di intelligenza artificiale NetApp
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Scopri le novità nelle soluzioni di intelligenza artificiale.



== 18 agosto 2025

Il sito NetApp Solutions è ora illink:https://docs.netapp.com/us-en/netapp-solutions-family/index.html["Famiglia di soluzioni NetApp"^] , che comprende i seguenti siti:

* Soluzioni di intelligenza artificiale NetApp
* link:https://docs.netapp.com/us-en/netapp-solutions-containers/index.html["Soluzioni container NetApp"^]
* link:https://docs.netapp.com/us-en/netapp-solutions-dataops/index.html["Soluzioni di gestione dei dati NetApp"^]
* link:https://docs.netapp.com/us-en/netapp-solutions-databases/index.html["Soluzioni di database NetApp"^]
* link:https://docs.netapp.com/us-en/netapp-solutions-cloud/index.html["Soluzioni cloud pubbliche e ibride NetApp"^]
* link:https://docs.netapp.com/us-en/netapp-solutions-sap/index.html["Soluzioni NetApp per SAP"^]
* link:https://docs.netapp.com/us-en/netapp-solutions-virtualization/index.html["Soluzioni di virtualizzazione NetApp"^]




== 3 dicembre 2025

Nuova soluzione:link:software/ai-hybrid-union.html["Distribuisci la formazione ibrida sull'intelligenza artificiale con Union.ai e NetApp FlexCache"]

Utilizza l'orchestrazione Union.ai con NetApp FlexCache per eseguire carichi di lavoro di formazione AI su GPU cloud, mantenendo al contempo i dati sensibili in locale.  FlexCache memorizza nella cache del cloud solo i dati necessari per un training ibrido efficiente e sicuro.
