---
sidebar: sidebar 
permalink: infra/ai-lenovo-train-conclusion.html 
keywords: acknowledgements, additional information 
summary: 'Questa soluzione NetApp e Lenovo è un"architettura flessibile e scalabile, ideale per l"ingresso nell"intelligenza artificiale aziendale di medio livello.  Lo storage NetApp garantisce prestazioni uguali o migliori dello storage SSD locale e offre i seguenti vantaggi a data scientist, data engineer e decision maker IT.' 
---
= Conclusione
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
La soluzione NetApp e Lenovo qui convalidata è un'architettura flessibile e scalabile, ideale per l'ingresso nell'intelligenza artificiale aziendale di medio livello.

Lo storage NetApp garantisce prestazioni uguali o migliori dello storage SSD locale e offre i seguenti vantaggi a data scientist, data engineer e decision maker IT:

* Condivisione semplice dei dati tra sistemi di intelligenza artificiale, analisi e altri sistemi aziendali critici.  Questa condivisione dei dati riduce il sovraccarico dell'infrastruttura, migliora le prestazioni e semplifica la gestione dei dati in tutta l'azienda.
* Elaborazione e archiviazione scalabili in modo indipendente per ridurre al minimo i costi e migliorare l'utilizzo delle risorse.
* Flussi di lavoro di sviluppo e distribuzione semplificati mediante snapshot e cloni integrati per spazi di lavoro utente istantanei e salvaspazio, controllo delle versioni integrato e distribuzione automatizzata.
* Protezione dei dati di livello aziendale per il disaster recovery e la continuità aziendale.




== Ringraziamenti

* Karthikeyan Nagalingam, Ingegnere tecnico di marketing, NetApp
* Jarrett Upton, amministratore, AI Lab Systems, Lenovo




== Dove trovare ulteriori informazioni

Per saperne di più sulle informazioni descritte nel presente documento, fare riferimento ai seguenti documenti e/o siti web:

* Pagina del prodotto NetApp All Flash Arrays
+
https://www.netapp.com/us/products/storage-systems/all-flash-array/aff-a-series.aspx["https://www.netapp.com/us/products/storage-systems/all-flash-array/aff-a-series.aspx"^]

* Pagina NetApp AFF A400
+
https://docs.netapp.com/us-en/ontap-systems/a400/index.html["https://docs.netapp.com/us-en/ontap-systems/a400/index.html"]

* Pagina del prodotto del software di gestione dati NetApp ONTAP
+
http://www.netapp.com/us/products/data-management-software/ontap.aspx["http://www.netapp.com/us/products/data-management-software/ontap.aspx"^]

* MLPerf
+
https://mlperf.org/["https://mlperf.org"^]

* Benchmark di TensorFlow
+
https://github.com/tensorflow/benchmarks["https://github.com/tensorflow/benchmarks"^]

* NVIDIA SMI (nvidia-smi)
+
https://developer.nvidia.com/nvidia-system-management-interface["https://developer.nvidia.com/nvidia-system-management-interface"]


