---
sidebar: sidebar 
permalink: infra/ai-lenovo-train-arch.html 
keywords: adjustments 
summary: 'La configurazione utilizzata per la convalida può essere adattata ad altri casi d"uso.' 
---
= Modifiche architettoniche
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
La configurazione utilizzata per questa convalida può essere adattata ad altri casi d'uso.



== Regolazioni della CPU

Per questa convalida abbiamo utilizzato un processore Skylake Intel Xeon Platinum 8360Y, come consigliato da Lenovo.  Ci aspettiamo che la CPU Cascade Lake equivalente, un processore Intel Xeon Gold 6330, offra prestazioni simili perché questo carico di lavoro non è vincolato alla CPU.



== Aumento della capacità di archiviazione

In base alle esigenze di capacità di archiviazione, è possibile aumentare lo spazio di archiviazione condiviso (volume NFS) su richiesta, a condizione di disporre di ulteriori modelli di controller e di ripiani per dischi.  È possibile eseguire questa operazione dalla CLI o dall'interfaccia Web NetApp del controller di storage come utente amministratore.
