---
sidebar: sidebar 
permalink: software/ai-conf-protopia-accuracy.html 
keywords: faceboxes, alpha value, accuracy, comparison 
summary: 'Per questa convalida, abbiamo eseguito l"inferenza per un caso d"uso di rilevamento delle immagini utilizzando un set di immagini grezze.  Abbiamo quindi eseguito lo stesso compito di inferenza sullo stesso set di immagini aggiungendo l"offuscamento Protopia prima dell"inferenza.  Abbiamo ripetuto l"attività utilizzando diversi valori di ALPHA per il componente di offuscamento di Protopia.' 
---
= Confronto dell'accuratezza dell'inferenza
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Per questa convalida, abbiamo eseguito l'inferenza per un caso d'uso di rilevamento delle immagini utilizzando un set di immagini grezze.  Abbiamo quindi eseguito lo stesso compito di inferenza sullo stesso set di immagini aggiungendo l'offuscamento Protopia prima dell'inferenza.  Abbiamo ripetuto l'attività utilizzando diversi valori di ALPHA per il componente di offuscamento di Protopia.  Nel contesto dell'offuscamento di Protopia, il valore ALPHA rappresenta la quantità di offuscamento applicata, dove un valore ALPHA più alto rappresenta un livello di offuscamento più elevato.  Abbiamo poi confrontato l'accuratezza dell'inferenza in queste diverse esecuzioni.

Le due tabelle seguenti forniscono dettagli sul nostro caso d'uso e ne descrivono i risultati.

Protopia collabora direttamente con i clienti per determinare il valore ALPHA appropriato per un caso d'uso specifico.

|===
| Componente | Dettagli 


| Modello | FaceBoxes (PyTorch) - 


| Set di dati | Set di dati FDDB 
|===
|===
| Offuscamento della protopia | ALFA | Precisione 


| NO | N / A | 0,9337148153739079 


| SÌ | 0,05 | 0,9028766627325002 


| SÌ | 0,1 | 0,9024301009661478 


| SÌ | 0,2 | 0,9081836283186224 


| SÌ | 0,4 | 0,9073066107482036 


| SÌ | 0,6 | 0,8847816568680239 


| SÌ | 0,8 | 0,8841195749171925 


| SÌ | 0,9 | 0,8455427675252052 


| SÌ | 0,95 | 0,8455427675252052 
|===