---
sidebar: sidebar 
permalink: software/ai-conf-protopia-usecases.html 
keywords: environmental intelligence, edge device wearables, noncombatant evacuation operations, cloud migration of analytics 
summary: 'L"elaborazione digitale delle immagini offre numerosi vantaggi, consentendo a molte organizzazioni di sfruttare al meglio i dati associati alle rappresentazioni visive.  Questa soluzione NetApp e Protopia fornisce un design di inferenza AI unico per proteggere e privatizzare i dati AI/ML durante l"intero ciclo di vita ML/DL.  Consente ai clienti di mantenere la proprietà dei dati sensibili, di utilizzare modelli di distribuzione cloud pubblici o ibridi per ottenere scalabilità ed efficienza, attenuando le preoccupazioni relative alla privacy, e di implementare l"inferenza AI all"edge.' 
---
= Aree di soluzione
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
L'elaborazione digitale delle immagini offre numerosi vantaggi, consentendo a molte organizzazioni di sfruttare al meglio i dati associati alle rappresentazioni visive.  Questa soluzione NetApp e Protopia fornisce un design di inferenza AI unico per proteggere e privatizzare i dati AI/ML durante l'intero ciclo di vita ML/DL.  Consente ai clienti di mantenere la proprietà dei dati sensibili, di utilizzare modelli di distribuzione cloud pubblici o ibridi per ottenere scalabilità ed efficienza, attenuando le preoccupazioni relative alla privacy, e di implementare l'inferenza AI all'edge.



== Intelligenza ambientale

Esistono molti modi in cui le industrie possono trarre vantaggio dall'analisi geospaziale nei settori dei rischi ambientali.  I governi e il dipartimento dei lavori pubblici possono ricavare informazioni utili sulla salute pubblica e sulle condizioni meteorologiche per fornire migliori consigli al pubblico durante una pandemia o un disastro naturale come gli incendi boschivi.  Ad esempio, è possibile identificare un paziente positivo al COVID in spazi pubblici, come aeroporti o ospedali, senza compromettere la privacy della persona interessata e avvisare le autorità competenti e il pubblico nelle vicinanze per le necessarie misure di sicurezza.



== Dispositivi indossabili Edge

In ambito militare e sui campi di battaglia, è possibile utilizzare l'inferenza dell'intelligenza artificiale sui dispositivi indossabili per monitorare la salute dei soldati, monitorare il comportamento dei conducenti e avvisare le autorità sulla sicurezza e sui rischi associati all'avvicinamento di veicoli militari, preservando e proteggendo al contempo la privacy dei soldati.  Il futuro dell'esercito è all'insegna dell'alta tecnologia con l'Internet of Battlefield Things (IoBT) e l'Internet of Military Things (IoMT) per equipaggiamenti da combattimento indossabili che aiutano i soldati a identificare i nemici e a ottenere prestazioni migliori in battaglia utilizzando il rapid edge computing.  Proteggere e preservare i dati visivi raccolti da dispositivi edge come droni e dispositivi indossabili è fondamentale per tenere a bada hacker e nemici.



== Operazioni di evacuazione non combattenti

Le operazioni di evacuazione dei non combattenti (NEO) sono condotte dal Dipartimento della Difesa per aiutare a evacuare cittadini e cittadini statunitensi, personale civile del Dipartimento della Difesa e persone designate (cittadini della nazione ospitante (HN) e cittadini di paesi terzi (TCN)) la cui vita è in pericolo verso un rifugio sicuro appropriato.  I controlli amministrativi in atto utilizzano in larga parte processi manuali di selezione degli sfollati.  Tuttavia, l'accuratezza, la sicurezza e la velocità dell'identificazione degli sfollati, del loro tracciamento e dello screening delle minacce potrebbero essere potenzialmente migliorate utilizzando strumenti di intelligenza artificiale/apprendimento automatico altamente automatizzati combinati con tecnologie di offuscamento video basate su intelligenza artificiale/apprendimento automatico.



== Assistenza sanitaria e ricerca biomedica

L'elaborazione delle immagini viene utilizzata per diagnosticare patologie ai fini della pianificazione chirurgica a partire da immagini 3D ottenute tramite tomografia computerizzata (TC) o risonanza magnetica (RM).  Le norme sulla privacy HIPAA disciplinano il modo in cui le organizzazioni devono raccogliere, elaborare e cancellare i dati di tutte le informazioni personali e le immagini digitali, come le fotografie.  Affinché i dati possano essere considerati condivisibili ai sensi delle normative HIPAA Safe Harbor, è necessario rimuovere le immagini fotografiche a viso intero e qualsiasi immagine comparabile.  Tecniche automatizzate come gli algoritmi di deidentificazione o di estrazione del cranio, utilizzati per oscurare i tratti del viso di un individuo dalle immagini strutturali TC/RM, sono diventate una parte essenziale del processo di condivisione dei dati per gli istituti di ricerca biomedica.



== Migrazione cloud dell'analisi AI/ML

Tradizionalmente i clienti aziendali hanno formato e distribuito modelli di intelligenza artificiale/apprendimento automatico in sede.  Per ragioni di economie di scala ed efficienza, questi clienti si stanno espandendo per spostare le funzioni di intelligenza artificiale/apprendimento automatico in implementazioni cloud pubbliche, ibride o multi-cloud.  Tuttavia, sono vincolati dai dati che possono essere esposti ad altre infrastrutture.  Le soluzioni NetApp affrontano una gamma completa di minacce alla sicurezza informatica richieste per https://www.netapp.com/data-protection/?internal_promo=mdw_aiml_ww_all_awareness-coas_blog["protezione dei dati"^] e valutazione della sicurezza e, se combinati con la trasformazione dei dati di Protopia, riducono al minimo i rischi associati alla migrazione dei carichi di lavoro di elaborazione delle immagini AI/ML sul cloud.

Per ulteriori casi d'uso per l'edge computing e l'inferenza dell'intelligenza artificiale in altri settori, vederelink:../infra/ai-lenovo-edge-intro.html["Inferenza AI TR-4886 al limite"^] e il blog NetApp AI, https://www.netapp.com/blog/federated-learning-intelligence-vs-privacy/["Intelligenza contro privacy"^] .
