---
sidebar: sidebar 
permalink: vector-db/ai-vdb-overview.html 
keywords: Solution Overview vector database 
summary: Panoramica della soluzione per la soluzione di database vettoriale per NetApp 
---
= Panoramica della soluzione
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Questa sezione fornisce una panoramica della soluzione di database vettoriale NetApp .



== Panoramica della soluzione

Questa soluzione mette in mostra i vantaggi e le capacità distintive che NetApp offre per affrontare le sfide che i clienti dei database vettoriali si trovano ad affrontare.  Sfruttando NetApp ONTAP, StorageGRID, le soluzioni cloud di NetApp e SnapCenter, i clienti possono aggiungere un valore significativo alle loro operazioni aziendali.  Questi strumenti non solo risolvono i problemi esistenti, ma migliorano anche l'efficienza e la produttività, contribuendo così alla crescita aziendale complessiva.



=== Perché NetApp?

* Le offerte di NetApp, come ONTAP e StorageGRID, consentono la separazione tra storage ed elaborazione, consentendo un utilizzo ottimale delle risorse in base a requisiti specifici.  Questa flessibilità consente ai clienti di scalare in modo indipendente il proprio storage utilizzando le soluzioni di storage NetApp .
* Sfruttando i controller di storage di NetApp, i clienti possono fornire in modo efficiente i dati al proprio database vettoriale utilizzando i protocolli NFS e S3.  Questi protocolli facilitano l'archiviazione dei dati dei clienti e gestiscono l'indice del database vettoriale, eliminando la necessità di più copie dei dati a cui si accede tramite metodi di file e oggetti.
* NetApp ONTAP fornisce supporto nativo per NAS e storage di oggetti attraverso i principali provider di servizi cloud come AWS, Azure e Google Cloud.  Questa ampia compatibilità garantisce un'integrazione perfetta, consentendo la mobilità dei dati dei clienti, l'accessibilità globale, il ripristino di emergenza, la scalabilità dinamica e le prestazioni elevate.
* Grazie alle solide funzionalità di gestione dei dati di NetApp, i clienti possono stare tranquilli sapendo che i loro dati sono ben protetti da potenziali rischi e minacce.  NetApp dà priorità alla sicurezza dei dati, offrendo ai clienti la tranquillità di sapere che le loro preziose informazioni sono al sicuro e integre.

